### ISSUE TITLE
Minor grammatical correction for new posts and pages

### ISSUE THREAD

**Issue by uyar** [getnikola/nikola-netlify-cms#10]
When adding a new post or page through Netlify CMS admin, the buttons read "New Posts" and "New Pages". To fix this, the label_singular setting can be used, as in:

```
collections:
  - name: "pages"
    label: "Pages"
    label_singular: "Page"
```
